example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

mywatchlist/urls.py
from django.urls import path
from  mywatchlist.views import show_watchlist
from  mywatchlist.views import show_xml
from  mywatchlist.views import show_json
from  mywatchlist.views import show_json_by_id
from  mywatchlist.views import show_xml_by_id

app_name = 'mywatchlist'

urlpatterns = [
    path('html/', show_watchlist, name='show_watchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax
from wishlist.views import submit_wishlist

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit', submit_wishlist, name='create_wishlist'),
]

example_app/models.py
from django.db import models

# Create your models here.

mywatchlist/models.py
from django.db import models

# Create your models here.
class Barangmywatchlist(models.Model):
    watched = models.TextField()
    title = models.TextField()
    rating = models.TextField()
    release_date = models.TextField()
    review = models.TextField()

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import Barangmywatchlist
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_watchlist(request):
    data_watchlist = Barangmywatchlist.objects.all()
    context = {
        'list_data_watchlist':data_watchlist,
        'nama': 'Rafli Wasis Anggito',
        'npm' : '2106751442'
    }

    return render(request, "watchlist.html", context)

def show_xml(request):
    data = Barangmywatchlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Barangmywatchlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request,id):
    data = Barangmywatchlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request,id):
    data = Barangmywatchlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
import json

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Rafli Wasis Anggito',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_wishlist_ajax(request):
    context = {
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "wishlist_ajax.html", context)

def submit_wishlist(request):
    if request.method == 'POST':
        nama_barang = request.POST['nama_barang']
        deskripsi = request.POST['deskripsi']
        harga_barang = request.POST['harga_barang']
        wishlist_instance = BarangWishlist(nama_barang=nama_barang, deskripsi=deskripsi, harga_barang=harga_barang)
        wishlist_instance.save()
        data = {
            "message": 'Successfully submitted'
        }
        json_object = json.dumps(data, indent = 4) 

        return JsonResponse(json.loads(json_object))
    return render(request, 'create_wishlist.html')


def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

mywatchlist/templates/watchlist.html
{% extends 'base.html' %}


{% block content %}
<!-- <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'> -->
<style>

table{
    table-layout: auto;
    width: 100%;
}
table, th, td {
    border: 1px solid black;
    border-collapse: separate; 
    margin: 15px 0;
    font-size: 0.9em;
    font-family: sans-serif;
    min-width: 100px; 
}

th, td {
    padding: 15px;  
}

th{
    background-color: #FDDF95;
}
</style>

<h1>Tugas 3 PBP</h1>
<h5>Nama: {{nama}} <br> NPM: {{npm}}  </h5>

<table>
    <tr>
    <th>Watched</th>
    <th>Title</th>
    <th>Rating</th>
    <th>Release Date</th>
    <th>Review</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for data in list_data_watchlist %}
    <tr>
        <td >{{data.watched}}</td>
        <td >{{data.title}}</td>
        <td >{{data.rating}}</td>
        <td >{{data.release_date}}</td>
        <td >{{data.review}}</td>
    </tr>
{% endfor %}
</table>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/create_wishlist.html
{% extends 'base.html' %} {% block meta %}
<title>Create Wishlist</title>

{% endblock meta %} {% block content %}

<div class="w-100 vh-100 d-flex justify-content-center align-items-center">
  <div
    class="d-flex flex-column align-items-center rounded-4 bg-light p-4 shadow-lg"
  >
    <h1>Create Wishlist</h1>

    <form method="POST" action="" class="d-flex flex-column">
      {% csrf_token %}
      <div class="d-flex flex-column mb-2">
        <label for="nama_barang">Nama Barang</label>
        <input
          type="text"
          name="nama_barang"
          id="nama_barang"
          placeholder="Nama Barang"
          class="form-control"
        />
      </div>
      <div class="d-flex flex-column mb-2">
        <label for="harga_barang">Harga Barang</label>
        <input
          name="harga_barang"
          id="harga_barang"
          placeholder="Harga Barang"
          class="form-control"
        />
      </div>
      <div class="d-flex flex-column mb-2">
        <label for="deskripsi">Deskripsi</label>
        <input
          name="deskripsi"
          id="deskripsi"
          placeholder="Deskripsi"
          class="form-control"
        />
      </div>
      <button class="btn btn-success">Submit</button>
      <button><a href="{% url 'wishlist:logout' %}">Logout</a></button>
    </form>

    <span id="message"></span>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $('form').submit(function (event) {
      const formData = {
        csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
        nama_barang: $('#nama_barang').val(),
        harga_barang: parseInt($('#harga_barang').val()),
        deskripsi: $('#deskripsi').val(),
      };

      $.ajax({
        type: 'POST',
        url: '/wishlist/ajax/submit',
        data: formData,
        dataType: 'json',
        encode: true,
      }).done(function (data) {
        $('#message').text(data.message);
      });

      event.preventDefault();
    });
  });
</script>
{% endblock content %}

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
{% load static %}
<link rel=”stylesheet” href="{% static '/css/style.css' %}">
{% endblock meta %}

{% block content %}
<style>
body{
background: rgb(104,221,164);
background: linear-gradient(90deg, rgba(104,221,164,1) 0%, rgba(145,145,205,1) 34%, rgba(107,111,223,1) 75%, rgba(65,164,184,1) 100%);
}

form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}

form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}

form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

input{
    display: block;
    height: 50px;
    width: 95%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}

button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
    
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
</style>





<div class = "login">
    <form method="POST" action="">
        {% csrf_token %}
        <h3>Login Here!</h3>

        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Username" >

        <label for="password">Password</label>
        <input type="password" name="password" placeholder="Password" class="form-control">

        <button type="submit" value="Login">Log In</button>
        <p>Don't have an account? <a href="{% url 'wishlist:register' %}"> Sign Up</a></p>

        {% if messages %}
            
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
            
        {% endif %}     
    </form>

        

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %} {% block content %}

<style>
  a{
    color: #ffffff;
  }
</style>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<script src="https://cdn.tailwindcss.com"></script>


<header>
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light sleep" id="ftco-navbar">
    <div class="container">
    <a class="navbar-brand" href="index.html">KRIBO APP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="oi oi-menu"></span> Menu
    </button>
    <div class="collapse navbar-collapse" id="ftco-nav">
    <ul class="navbar-nav ml-auto">
    <li class="nav-item active"><a href="index.html" class="nav-link">Home</a></li>
    <li class="nav-item"><a href="about.html" class="nav-link">About</a></li>
    <li class="nav-item"><a href="contact.html" class="nav-link">Contact Us</a></li>
    </ul>
    </div>
    </div>
    </nav>

  <!-- Hero -->
</header>
<section class="pt-24 bg-white"; style="background-image: linear-gradient( 95.2deg, rgba(173,252,234,1) 26.8%, rgba(192,229,246,1) 64% );">
  <div class="px-12 mx-auto max-w-7xl">
      <div class="w-full mx-auto text-left md:w-11/12 xl:w-9/12 md:text-center">
          <h1 class="mb-8 text-4xl font-extrabold leading-none tracking-normal text-gray-900 md:text-6xl md:tracking-tight">
              <span>Check</span> <span class="block w-full py-2 text-transparent bg-clip-text leading-12 bg-gradient-to-r from-green-400 to-purple-500 lg:inline">Your Wishlist!</span>
          </h1>
          <div class="mb-4 space-x-0 md:space-x-2 md:mb-8">
              <a href="{% url 'wishlist:create_wishlist'%}" class="inline-flex items-center justify-center w-full px-6 py-3 mb-2 text-lg text-white bg-green-400 rounded-2xl sm:w-auto sm:mb-0">
                  Add Task
              </a>
          </div>
      </div>
      <div class="w-full mx-auto mt-20 text-center md:w-10/12">
          <div class="relative z-0 w-full mt-8">
              <div class="relative overflow-hidden shadow-2xl">
              </div>
          </div>
      </div>
  </div>
</section>

<body style="background-image: linear-gradient( 95.2deg, rgba(173,252,234,1) 26.8%, rgba(192,229,246,1) 64% );">
  <br>
  <div>
    <table class="table table-striped">
      <thead class="table-dark">
        <tr>
          <th scope="col">Nama Barang</th>
          <th scope="col">Harga Barang</th>
          <th scope="col">Deskripsi</th>
        </tr>
      </thead>
      <tbody id="table-body"></tbody>
    </table>
  </div>
  
  <button><a href="{% url 'wishlist:logout'%}"class="btn btn-success">Logout</a></button>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
    $(document).ready(function () {
        $.get('/wishlist/json', function (data) {
        data.map((singleData) =>
            $('#table-body').append(`<tr>
        <td>${singleData.fields.nama_barang}</td>
        <td>${singleData.fields.harga_barang}</td>
        <td>${singleData.fields.deskripsi}</td>
    </tr>`)
        );
        });
    });
    </script>


</body>




<footer class="text-center text-lg-start bg-white text-muted"; style="background-image: linear-gradient( 95.2deg, rgba(173,252,234,1) 26.8%, rgba(192,229,246,1) 64% );">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 link-secondary">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3 text-secondary"></i>Kribo App
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3 text-secondary"></i> Indonesia, Jakarta Selatan</p>
          <p>
            <i class="fas fa-envelope me-3 text-secondary"></i>
            rafliwasisanggito@gmail.com
          </p>
          <p><i class="fas fa-phone me-3 text-secondary"></i> + 01 234 567 88</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
    © 2022
    <a class="text-reset fw-bold" >Kribo App</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->


{% endblock content %}